[platformio]
default_envs = esp32s3_n16r8

[env:esp32s3_n16r8]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.arduino.partitions = default_16MB.csv

; 无需外部库 — BLE + LEDC PWM 都是 ESP32 内置

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM

; 上传
upload_speed = 115200
