name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq openjdk-17-jdk-headless python3-pip
          sudo pip3 install buildozer cython --break-system-packages

      - name: Build APK
        run: |
          cd ${{ github.workspace }}
          JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DeskCat-APK
          path: bin/*.apk
